name: marsbazaar
description: Internal lead mobile app

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  # Localisation
  intl: ^0.17.0
  # Shared Preferences
  shared_preferences: ^2.0.15
  # Launcher
  flutter_app_name: ^0.1.1
  flutter_launcher_icons: ^0.11.0

flutter_app_name:
  name: "MarsBazaar Internal Lead App"
flutter_icons:
  image_path: "assets/logo.png"
  android: true
  ios: true

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/logo_expanded.png
    - assets/logo_expanded_big.png
    - assets/login_onboard.png
    - assets/login_overlay_br.png
    - assets/login_overlay_tr.png
    - assets/logo.png
  fonts:
   - family: Maven Pro
     fonts:
       - asset: assets/MavenPro-Medium.ttf
       - asset: assets/MavenPro-SemiBold.ttf
       - asset: assets/MavenPro-ExtraBold.ttf
       - asset: assets/MavenPro-Bold.ttf
       - asset: assets/MavenPro-Regular.ttf
       - asset: assets/MavenPro-Black.ttf

